import { ThemeProvider } from '@/components/ui/theme/provider';

import '../styles/globals.css';
import '../styles/globals.scss';
import '@total-typescript/ts-reset';

import type { Metadata } from 'next';

import React from 'react';

import BottomNavigation from '@/components/navigation/bottom';
import TopNavigation from '@/components/navigation/top';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <TopNavigation />

          <main className='h-full w-full px-2.5'>
            <div className='flex h-full w-full flex-col rounded-t-md border-l border-r border-t bg-background-secondary shadow-md'>
              {children}
            </div>
          </main>

          <BottomNavigation />
        </ThemeProvider>
      </body>
    </html>
  );
}
